### ISSUE TITLE
Demo not working?

### ISSUE THREAD

**Issue by redstreet** [elazar/ledger-stats#2]
The demo at http://matthewturland.com/ledger-stats/ doesn't seem to work. For any dates  I put in, I get very many pages of this:

Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/mturland/sites/matthewturland.com/public/ledger-stats/index.php on line 265 Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/mturland/sites/matthewturland.com/public/ledger-stats/index.php on line 267 Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning,

**Comment by elazar** [comment]
Fixed. Thanks for the report.
